### ISSUE TITLE
How to create beautiful Figure 3?

### ISSUE THREAD

**Issue by ucalyptus2** [BERYLSHEEP/AdvStyle#3]
@BERYLSHEEP Paper's Figure 3 is beautiful. How to create it?

**Comment by BERYLSHEEP** [comment]
Using the Microsoft Visio.

**Comment by BERYLSHEEP** [comment]
I also add a demo file on my project. (https://github.com/BERYLSHEEP/AdvStyle/blob/master/stylegan.vsdx)
